### PR TITLE
deepdiff v3.3.0 last version for py2 support

### PR DESCRIPTION
**Pull request by digitronik**
Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

### CODE REVIEW

**Comment by digitronik** [comment]
Ignore travis need to fix test.

**Comment by mshriver** [comment]
@digitronik I'm opening another PR to fix that test.

**Comment by mshriver** [comment]
Unit tests should be fixed by #18

**Comment by mshriver** [comment]
Please rebase, and travis should pass 100% now.

**Pull request merged**
